<!DOCTYPE html>
<html lang="en">
<head>
 
  <script src="https://js.stripe.com/v3/"></script>
  <script src="cart.js"></script>
</head>
<body>
  <?php
  session_start();

  // Check if cart items exist in session
  $cartItems = isset($_SESSION['cart_items']) ? $_SESSION['cart_items'] : array();

  // Calculate total price
  $totalPrice = 0;
  foreach ($cartItems as $cartItem) {
    $totalPrice += $cartItem['price'];
  }

  // Define your Stripe API keys
  $stripePublicKey = 'pk_test_51NIn9fSCMx4NNjOmPAUlHd4DkCgOq2mAkFB9vIgNWJnDCBnVfaCwiXvorGjRsUXpt5MwGhoXcMhFYugHYFsgTtej00rNEOWNy8';
  $stripeSecretKey = 'sk_test_51NIn9fSCMx4NNjOmUXlJ2pGfn0QK4gRMMVTf08DNfVfPvVIGZZxmugztn60XOfOUWV2nGHri0NrTExhHU5u65UJw00VOqOKb80';

  if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Include Stripe library
    require_once('vendor/autoload.php');

    \Stripe\Stripe::setApiKey($stripeSecretKey);

    // Retrieve POST data from the payment form
    $name = $_POST['name'];
    $email = $_POST['email'];
    $amount = $totalPrice * 100; // Convert amount to cents (Stripe uses cents)

    // Create a charge
    try {
      $charge = \Stripe\Charge::create([
        'amount' => $amount,
        'currency' => 'usd',
        'description' => 'Payment for products',
        'source' => $_POST['stripeToken'], // Token generated by Stripe.js
        'metadata' => [
          'name' => $name,
          'email' => $email
        ]
      ]);

      // Payment successful, you can store relevant information in your database or perform other actions
      echo 'Payment successful! Charge ID: ' . $charge->id;
      
      // Clear the cart after successful payment
      unset($_SESSION['cart_items']);
    } catch (\Stripe\Exception\CardException $e) {
      // Card was declined or other error occurred
      echo 'Payment failed: ' . $e->getMessage();
    }
  }
  ?>

  <div class="container">
    <!-- Display cart items -->
    <h2>YOUR PERSONAL BAG</h2>
    <?php if (!empty($cartItems)) : ?>
      <table>
        <tr>
          <th>Image</th>
          <th>Product</th>
          <th>Price</th>
          <th>Action</th>
        </tr>
        <?php $totalQuantity = 0; ?>
        <?php foreach ($cartItems as $cartItem) : ?>
          <tr>
            <td><img src="<?php echo $cartItem['image']; ?>" alt="<?php echo $cartItem['name']; ?>" class="product-image"></td>
            <td><?php echo $cartItem['name']; ?></td>
            <td><?php echo $cartItem['price']; ?></td>
            <td><a href="remove_from_cart.php?id=<?php echo $cartItem['id']; ?>">Remove</a></td>
          </tr>
          <?php $totalQuantity++; ?>
        <?php endforeach; ?>
      </table>
      <p>Total quantity: <?php echo $totalQuantity; ?></p>
      <p>Total price: $<?php echo $totalPrice; ?></p>
      <p><li><a href="products.php">CLICK TO ADD MORE!!</a></li></p>
      <!-- Payment form -->
      <h2>Payment</h2>
      <form id="payment-form" action="payment_processing.php" method="POST">
        <label for="name">Name:</label>
        <input type="text" name="name" required><br><br>
        <label for="email">Email:</label>
        <input type="email" name="email" required><br><br>

        <!-- Card element -->
        <div id="card-element"></div>
        <div id="card-errors"></div>

        <button onclick="displayMessage()">Pay Now</button>
  <script>
    function displayMessage() {
      alert("Payment is in process !"); // Change this message to the desired one
    }
  </script>
      </form>

      <script>
        var stripe = Stripe('<?php echo $stripePublicKey; ?>');
        var elements = stripe.elements();
        var style = {
          base: {
            fontSize: '16px',
            color: '#32325d',
            '::placeholder': {
              color: '#aab7c4'
            }
          }
        };
        var card = elements.create('card', { style: style });
        card.mount('#card-element');
        var form = document.querySelector('#payment-form');
        form.addEventListener('submit', function(event) {
          event.preventDefault();
          stripe.createToken(card).then(function(result) {
            if (result.error) {
              var errorElement = document.getElementById('card-errors');
              errorElement.textContent = result.error.message;
            } else {
              stripeTokenHandler(result.token);
            }
          });
        });
      </script>
    <?php else : ?>
      <p>Your cart is empty. <a href="products.php">Go to Shop some products</a></p>
    <?php endif; ?>
  </div>
<style>
/* Global Styles */
body{
  background-image: url('dyvaol.jpg');
  background-repeat: no-repeat;
  background-size: cover;	
}

  .container {
    max-width: 1200px;
    height:600px;
    margin: 0 auto;
    padding: 20px;
  }
  
  /* Cart Styles */
  h2 {
    text-align: center;
    margin-top: 20px;
    color: #333;
  }
  
  table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 20px;
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    background-color: #fff;
  }
  
  th,
  td {
    padding: 10px;
    text-align: left;
  }
  
  th {
    background-color: #f2f2f2;
    color: #333;
    font-weight: bold;
  }
  
  tr:nth-child(even) {
    background-color: #f9f9f9;
  }
  
  tr:hover {
    background-color: #f1f1f1;
  }
  
  a {
    color: #ff0000;
    text-decoration: none;
  }
  
  a:hover {
    text-decoration: underline;
  }
  
  .total {
    text-align: right;
    margin-top: 20px;
    font-weight: bold;
    color: #333;
  }
  
  .empty-cart {
    text-align: center;
    margin-top: 20px;
    color: #777;
  }
  
  /* Colorful Styles */
  .container {
    background-color:white;
    border-radius: 10px;
  }
  
  h2 {
    color: red;
  }
  
  table {
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
    background-color: #fff;
  }
  
  th {
    background-color: #4287f5;
    color: black;
  }
  
  tr:nth-child(even) {
    background-color: #e7f3ff;
  }
  
  tr:hover {
    background-color: #d6eaff;
  }
  
  a {
    color: #ff5959;
  }
  
  .total {
    color: #333;
  }
  
  .empty-cart {
    color: #888;
  }
  
  .product-image {
    max-width: 100px;
    max-height: 100px;
  }
  
</style>
</body>
</html>
